import 'package:equatable/equatable.dart';

import 'enums.dart';
import 'reward_risk_ratio.dart';

/// A trade recommendation generated by the valuations engine.
class Recommendation extends Equatable {
  final String symbol;
  final String assetName;
  final TradeDirection direction;
  final TradeCategory category;
  final double entryPrice;
  final double targetPrice;
  final double stopLossPrice;
  final RewardRiskRatio rewardRisk;
  final DateTime generatedAt;
  final RecommendationStatus status;

  const Recommendation({
    required this.symbol,
    required this.assetName,
    required this.direction,
    required this.category,
    required this.entryPrice,
    required this.targetPrice,
    required this.stopLossPrice,
    required this.rewardRisk,
    required this.generatedAt,
    required this.status,
  });

  /// Creates a copy with updated fields.
  Recommendation copyWith({
    String? symbol,
    String? assetName,
    TradeDirection? direction,
    TradeCategory? category,
    double? entryPrice,
    double? targetPrice,
    double? stopLossPrice,
    RewardRiskRatio? rewardRisk,
    DateTime? generatedAt,
    RecommendationStatus? status,
  }) {
    return Recommendation(
      symbol: symbol ?? this.symbol,
      assetName: assetName ?? this.assetName,
      direction: direction ?? this.direction,
      category: category ?? this.category,
      entryPrice: entryPrice ?? this.entryPrice,
      targetPrice: targetPrice ?? this.targetPrice,
      stopLossPrice: stopLossPrice ?? this.stopLossPrice,
      rewardRisk: rewardRisk ?? this.rewardRisk,
      generatedAt: generatedAt ?? this.generatedAt,
      status: status ?? this.status,
    );
  }

  @override
  List<Object?> get props => [
        symbol,
        assetName,
        direction,
        category,
        entryPrice,
        targetPrice,
        stopLossPrice,
        rewardRisk,
        generatedAt,
        status,
      ];
}
